"""Campaigns — a recipe-run wrapped as a three-click batch outreach flow.

A campaign is a named wrapper around ONE sourcing session (the leads that one
recipe run inserted). Lifecycle:

  create → (session linked when the run inserts leads) → reviewing →
          (human keyboard review of the queue) → shipped

Ship (in app.campaign_ship) is NOT a send: it batches the approved queue leads
onto concrete send dates via capacity.schedule_by_capacity, then produces
Instantly-format CSV files (one per send date) and records every exported lead
in the DNC registry + export_history so the next batch's dedup treats them as
sent. Delivery itself is left to whatever send path the user wires up, exactly
as with the existing /download/instantly.csv export — no Gmail/Sim, no SMTP,
no Apollo enrol (Apollo has no create/list/enroll wiring).

Statuses: `reviewing` → `shipped` (never re-opened; a campaign ships once).
"""

from __future__ import annotations

from datetime import datetime, timezone


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def ensure_table(conn) -> None:
    """PostgreSQL DDL — COURSE-GUARDED (see tests/test_campaigns.py): the PG
    wrapper can't translate SQLite's AUTOINCREMENT idiom, so this must stay
    PG-identity only; sqlite (test harness) stubs ensure_table and builds its
    own compat table."""
    conn.execute(
        "CREATE TABLE IF NOT EXISTS campaigns ("
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
        "recipe_id BIGINT, "
        "session_id BIGINT, "
        "name TEXT, "
        "status TEXT NOT NULL DEFAULT 'reviewing', "
        "created_at TEXT, "
        "shipped_at TEXT, "
        "ship_plan TEXT"
        ")"
    )
    conn.commit()


def create(conn, recipe_id: int | None, name: str | None = None) -> int:
    ensure_table(conn)
    row = conn.execute(
        "INSERT INTO campaigns (recipe_id, name, status, created_at) "
        "VALUES (?, ?, 'reviewing', ?) RETURNING id",
        (recipe_id, name, _now()),
    ).fetchone()
    conn.commit()
    return row["id"]


def get(conn, campaign_id: int) -> dict | None:
    ensure_table(conn)
    row = conn.execute("SELECT * FROM campaigns WHERE id = ?", (campaign_id,)).fetchone()
    if row is None:
        return None
    d = dict(row)
    d["filters"] = {}
    return d


def list_all(conn) -> list[dict]:
    ensure_table(conn)
    rows = conn.execute("SELECT * FROM campaigns ORDER BY id DESC").fetchall()
    return [dict(r) for r in rows]


def set_session(conn, campaign_id: int, session_id: int) -> None:
    ensure_table(conn)
    conn.execute("UPDATE campaigns SET session_id = ? WHERE id = ?", (session_id, campaign_id))
    conn.commit()


def set_status(conn, campaign_id: int, status: str) -> None:
    ensure_table(conn)
    conn.execute("UPDATE campaigns SET status = ? WHERE id = ?", (status, campaign_id))
    conn.commit()


def mark_shipped(conn, campaign_id: int, ship_plan: str | None = None) -> None:
    """Freezes the campaign at `shipped`. A campaign ships once; a second Ship
    call is refused by the route (idempotence), never re-opened here.
    ship_plan is the JSON batch schedule the Ship route computed, kept so batch
    CSVs can be re-generated on demand for audit."""
    ensure_table(conn)
    conn.execute(
        "UPDATE campaigns SET status = 'shipped', shipped_at = ?, ship_plan = ? WHERE id = ?",
        (_now(), ship_plan, campaign_id),
    )
    conn.commit()