"""Saved Apollo search recipes with historical yield.

Your validated finding: vertical keyword searches ("health app", "hr platform")
yield 80-100% qualified but tiny pools; generic keywords yield huge pools at
~45% qualified with ~25% competitors. Implication: run MANY narrow searches,
not a few broad ones — so recipes must be first-class, named, versioned, and
carry their own track record so the UI can say "this recipe yields 85%
qualified but 0% replies".

A recipe stores the Apollo search `filters` (passed straight to
apollo_client.search_people) plus running counters updated as batches flow
through: runs, leads_pulled, qualified, enriched, sent, replies.
"""
from __future__ import annotations

import json
from datetime import datetime, timezone


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def ensure_table(conn) -> None:
    """Creates apollo_recipes + apollo_recipe_versions if missing.

    Backend-tolerant: the app runs on PostgreSQL (identity columns), the
    offline test-suite runs on sqlite (which rejects IDENTITY syntax). Try
    the PG DDL first; on a sqlite syntax error fall back to sqlite DDL.
    Both are no-ops when the tables already exist (init_db creates them).
    """
    cols = ("name TEXT, filters TEXT, created_at TEXT, "
            "runs INTEGER NOT NULL DEFAULT 0, leads_pulled INTEGER NOT NULL DEFAULT 0, "
            "qualified INTEGER NOT NULL DEFAULT 0, enriched INTEGER NOT NULL DEFAULT 0, "
            "sent INTEGER NOT NULL DEFAULT 0, replies INTEGER NOT NULL DEFAULT 0")
    vcols = ("recipe_id BIGINT NOT NULL, version INTEGER NOT NULL, filters TEXT, created_at TEXT, "
             "runs INTEGER NOT NULL DEFAULT 0, leads_pulled INTEGER NOT NULL DEFAULT 0, "
             "qualified INTEGER NOT NULL DEFAULT 0, enriched INTEGER NOT NULL DEFAULT 0, "
             "sent INTEGER NOT NULL DEFAULT 0, replies INTEGER NOT NULL DEFAULT 0")
    for pk in ("id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", "id INTEGER PRIMARY KEY"):
        try:
            conn.execute(f"CREATE TABLE IF NOT EXISTS apollo_recipes ({pk}, {cols})")
            conn.execute(f"CREATE TABLE IF NOT EXISTS apollo_recipe_versions ({pk}, {vcols})")
            conn.commit()
            return
        except Exception:
            try:
                conn.rollback()
            except Exception:
                pass
            continue
    raise RuntimeError("could not create apollo_recipes tables on this backend")


def create(conn, name: str, filters: dict) -> int:
    ensure_table(conn)
    row = conn.execute(
        "INSERT INTO apollo_recipes (name, filters, created_at) VALUES (?, ?, ?) RETURNING id",
        (name, json.dumps(filters, ensure_ascii=False), _now()),
    ).fetchone()
    rid = row["id"]
    # Version 1 snapshot of this recipe's filters (empty yield until first run).
    conn.execute(
        "INSERT INTO apollo_recipe_versions (recipe_id, version, filters, created_at) "
        "VALUES (?, ?, ?, ?)",
        (rid, 1, json.dumps(filters, ensure_ascii=False), _now()),
    )
    conn.commit()
    return rid

def update_filters(conn, recipe_id: int, filters: dict) -> None:
    """Edits a recipe's filters as a NEW version (Task 13: versioned objects).

    The OLD filters + their cumulative yield stay frozen as their own version
    row (historical yield), while a new version for the new filters inherits the
    cumulative counters and keeps growing. versions() returns them in order."""
    ensure_table(conn)
    cur = get(conn, recipe_id)
    if cur is None:
        raise ValueError(f"recipe {recipe_id} not found")
    next_ver = (versions(conn, recipe_id) or [{}])[-1].get("version", 0) + 1
    conn.execute(
        "INSERT INTO apollo_recipe_versions (recipe_id, version, filters, created_at, "
        "runs, leads_pulled, qualified, enriched, sent, replies) "
        "SELECT ?, ?, ?, created_at, runs, leads_pulled, qualified, "
        "enriched, sent, replies FROM apollo_recipes WHERE id = ?",
        (recipe_id, next_ver, json.dumps(filters, ensure_ascii=False), recipe_id),
    )
    conn.execute(
        "UPDATE apollo_recipes SET filters = ?, created_at = ? WHERE id = ?",
        (json.dumps(filters, ensure_ascii=False), _now(), recipe_id),
    )
    conn.commit()


def versions(conn, recipe_id: int) -> list[dict]:
    """Historical, ordered yield for the recipe — one element per filters
    version, each carrying that version's cumulative counters."""
    ensure_table(conn)
    rows = conn.execute(
        "SELECT * FROM apollo_recipe_versions WHERE recipe_id = ? ORDER BY version ASC",
        (recipe_id,),
    ).fetchall()
    out = []
    for row in rows:
        d = dict(row)
        try:
            d["filters"] = json.loads(d["filters"]) if d.get("filters") else {}
        except (json.JSONDecodeError, TypeError):
            d["filters"] = {}
        d["qualified_rate"] = round(d["qualified"] / d["leads_pulled"], 2) if d["leads_pulled"] else None
        d["reply_rate"] = round(d["replies"] / d["sent"], 3) if d["sent"] else None
        out.append(d)
    return out


def get(conn, recipe_id: int) -> dict | None:
    ensure_table(conn)
    row = conn.execute("SELECT * FROM apollo_recipes WHERE id = ?", (recipe_id,)).fetchone()
    if not row:
        return None
    d = dict(row)
    try:
        d["filters"] = json.loads(d["filters"]) if d.get("filters") else {}
    except (json.JSONDecodeError, TypeError):
        d["filters"] = {}
    d["qualified_rate"] = round(d["qualified"] / d["leads_pulled"], 2) if d["leads_pulled"] else None
    d["reply_rate"] = round(d["replies"] / d["sent"], 3) if d["sent"] else None
    return d


def list_all(conn) -> list[dict]:
    ensure_table(conn)
    rows = conn.execute("SELECT * FROM apollo_recipes ORDER BY id DESC").fetchall()
    out = []
    for row in rows:
        d = dict(row)
        try:
            d["filters"] = json.loads(d["filters"]) if d.get("filters") else {}
        except (json.JSONDecodeError, TypeError):
            d["filters"] = {}
        d["qualified_rate"] = round(d["qualified"] / d["leads_pulled"], 2) if d["leads_pulled"] else None
        d["reply_rate"] = round(d["replies"] / d["sent"], 3) if d["sent"] else None
        out.append(d)
    return out


def record_run(conn, recipe_id: int, *, leads_pulled: int, qualified: int,
               enriched: int) -> None:
    """Update a recipe's counters after a sourcing run (one search + prefilter
    + enrich cycle)."""
    ensure_table(conn)
    conn.execute(
        "UPDATE apollo_recipes SET runs = runs + 1, "
        "leads_pulled = leads_pulled + ?, qualified = qualified + ?, "
        "enriched = enriched + ? WHERE id = ?",
        (leads_pulled, qualified, enriched, recipe_id),
    )
    conn.execute(
        "UPDATE apollo_recipe_versions SET runs = runs + 1, "
        "leads_pulled = leads_pulled + ?, qualified = qualified + ?, "
        "enriched = enriched + ? "
        "WHERE recipe_id = ? AND version = (SELECT MAX(version) FROM apollo_recipe_versions WHERE recipe_id = ?)",
        (leads_pulled, qualified, enriched, recipe_id, recipe_id),
    )
    conn.commit()


def record_outcomes(conn, recipe_id: int, *, sent: int = 0, replies: int = 0) -> None:
    """Update send/reply counters (from the sending tool / Apollo analytics)."""
    ensure_table(conn)
    conn.execute(
        "UPDATE apollo_recipes SET sent = sent + ?, replies = replies + ? WHERE id = ?",
        (sent, replies, recipe_id),
    )
    conn.execute(
        "UPDATE apollo_recipe_versions SET sent = sent + ?, replies = replies + ? "
        "WHERE recipe_id = ? AND version = (SELECT MAX(version) FROM apollo_recipe_versions WHERE recipe_id = ?)",
        (sent, replies, recipe_id, recipe_id),
    )
    conn.commit()


def delete(conn, recipe_id: int) -> None:
    ensure_table(conn)
    conn.execute("DELETE FROM apollo_recipes WHERE id = ?", (recipe_id,))
    conn.execute("DELETE FROM apollo_recipe_versions WHERE recipe_id = ?", (recipe_id,))
    conn.commit()
