"""apollo_analytics (Task 13) — offline guards.

DDL must be PG-identity (sqlite can't run it — same guard as campaigns). HTTP is
isolated in _get, so the sweep + fold runs against a sqlite harness with a
stubbed ensure_report_table and its own compat tables (the project's standard
pattern, see test_campaigns.py / test_campaign_flow.py).
"""
import sqlite3

import pytest

import apollo_analytics as aa


class _CapturingConn:
    def __init__(self):
        self.executed = []

    def execute(self, sql, params=None):
        self.executed.append(sql)
        return self

    def commit(self):
        pass


def test_ensure_report_table_ddl_is_postgres_only():
    conn = _CapturingConn()
    aa.ensure_report_table(conn)
    ddl = conn.executed[0]
    assert "AUTOINCREMENT" not in ddl
    assert "?" not in ddl
    assert "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in ddl
    assert ddl.startswith("CREATE TABLE IF NOT EXISTS apollo_analytics_sync_report")


def test_ensure_report_table_is_idempotent_via_schema_and_guard():
    # Both the startup migration (db._schema_sql) and the module guard share
    # the same table name; dupes must never be created.
    assert "apollo_analytics_sync_report" in __import__("db")._schema_sql()


def _sqlite_conn():
    conn = sqlite3.connect(":memory:")
    conn.row_factory = sqlite3.Row
    conn.execute("""
        CREATE TABLE leads (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            session_id INTEGER, email TEXT, email_sent_at TEXT
        )
    """)
    conn.execute("""
        CREATE TABLE lead_outcomes (
            lead_id INTEGER PRIMARY KEY,
            email TEXT, channel TEXT, recipe_id INTEGER, sent_at TEXT,
            opened INTEGER, clicked INTEGER, replied INTEGER, reply_sentiment TEXT,
            meeting_booked INTEGER, closed_won INTEGER, revenue REAL,
            created_at TEXT, updated_at TEXT
        )
    """)
    conn.execute("""
        CREATE TABLE apollo_analytics_sync_report (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            month TEXT, fetched_at TEXT, apollo_message_id TEXT,
            to_email TEXT, emailer_campaign_id TEXT, sent_at TEXT, status TEXT,
            opened INTEGER, clicked INTEGER, replied INTEGER,
            reply_sentiment TEXT, raw_json TEXT,
            UNIQUE(month, apollo_message_id)
        )
    """)
    conn.commit()
    return conn


# ---------------------------------------------------------------------------
# parse_outreach_email
# ---------------------------------------------------------------------------

def test_parse_outreach_email_maps_flags_and_sentiment():
    msg = {
        "id": "m1",
        "to_email": "alice@co.com",
        "status": "opened",
        "sent_at": "2026-09-01T10:00:00Z",
        "opens": 2,
        "clicks": 1,
        "replied": True,
        "reply_class": "willing_to_meet",
        "emailer_campaign_id": "camp-7",
    }
    r = aa.parse_outreach_email(msg)
    assert r["email"] == "alice@co.com"
    assert r["opened"] == 1 and r["clicked"] == 1 and r["replied"] == 1
    assert r["reply_sentiment"] == "willing_to_meet"
    assert r["campaign_id"] == "camp-7"


def test_parse_outreach_email_falls_back_to_recipients():
    msg = {"id": "m2", "recipients": [{"email": "Bob@X.COM ", "raw_name": "Bob"}],
           "status": "delivered", "opened_at": None}
    r = aa.parse_outreach_email(msg)
    assert r["email"] == "bob@x.com"  # lowercased + stripped
    assert r["opened"] == 0 and r["clicked"] == 0 and r["replied"] == 0


def test_message_skippable_drafts_scheduled():
    assert aa._message_skippable({"status": "scheduled"})
    assert aa._message_skippable({"status": "drafted"})
    assert not aa._message_skippable({"status": "delivered"})
    assert not aa._message_skippable({"status": None})


# ---------------------------------------------------------------------------
# Query Analytics Report helpers
# ---------------------------------------------------------------------------

def test_build_sync_report_payload_custom_window():
    p = aa.build_sync_report_payload(start="2026-08-01", end="2026-08-31", group_by="emailer_campaign_id")
    assert p["date_ranges"] == [{"modality": "custom_range"}]
    assert p["filters"] == {"smart_datetime_range": {"min": "2026-08-01", "max": "2026-08-31"}}
    assert p["group_by"] == [{"name": "emailer_campaign_id"}]
    assert {m["value"] for m in p["metrics"]} == {
        "num_emails_sent", "num_emails_opened", "num_emails_clicked", "num_emails_replied"}


def test_build_sync_report_payload_preset_window():
    p = aa.build_sync_report_payload()
    assert p["date_ranges"][0]["modality"] == "last_30_days"
    assert p["filters"] == {}
    assert p["group_by"] == []


def test_parse_sync_report_flattens_buckets_and_drops_total():
    data = {"response": {"table_response": {"emailer_campaign_id": {"buckets": [
        {"key": "c1", "readable_key": "Q2 Outreach", "num_emails_sent": 100,
         "num_emails_opened": 60, "num_emails_clicked": 10, "num_emails_replied": 8},
        {"key": "total", "readable_key": "Total", "num_emails_sent": 100, "num_emails_replied": 8},
    ]}}}}
    rows = aa.parse_sync_report(data)
    assert len(rows) == 1
    assert rows[0]["key"] == "c1"
    assert rows[0]["num_emails_sent"] == 100
    assert rows[0]["num_emails_replied"] == 8


# ---------------------------------------------------------------------------
# sync_analytics_report — full sweep + fold (offline _get)
# ---------------------------------------------------------------------------

def test_sync_requires_api_key(monkeypatch):
    # apollo_client loads .env on import; make sure no real key leaks in from
    # the environment, otherwise the missing-key branch is never exercised.
    monkeypatch.delenv("APOLLO_API_KEY", raising=False)
    conn = _sqlite_conn()
    with pytest.raises(aa.ApolloAnalyticsError):
        aa.sync_analytics_report(conn, key="", _get=lambda *a, **kw: {})


def test_sync_sweeps_pages_saves_report_and_folds_outcomes(monkeypatch):
    conn = _sqlite_conn()
    conn.execute("INSERT INTO leads (id, session_id, email) VALUES (1, 1, 'alice@co.com')")
    conn.commit()
    monkeypatch.setattr(aa, "ensure_report_table", lambda c: None)

    pages = iter([
        {"emailer_messages": [
            {"id": "m1", "to_email": "alice@co.com", "status": "opened",
             "sent_at": "2026-09-05T10:00:00Z", "opens": 1, "clicks": 1, "replied": True,
             "reply_class": "willing_to_meet", "emailer_campaign_id": "c1"},
            {"id": "m2", "to_email": "nobody@nowhere.com", "status": "delivered",
             "sent_at": "2026-09-05T11:00:00Z"},
            {"id": "m3", "to_email": "old@co.com", "status": "delivered",
             "sent_at": "2020-01-01T10:00:00Z"},  # older than the window -> skipped
            {"id": "m4", "status": "drafted"},     # not sent -> skipped
        ], "pagination": {"total_pages": 2}},
        {"emailer_messages": [], "pagination": {"total_pages": 2}},
    ])

    def _fake_get(path, params, key):
        assert path == aa.SEARCH_EMAILS_PATH
        assert key == "secret"
        return next(pages)

    result = aa.sync_analytics_report(conn, key="secret", days=7, _get=_fake_get)
    assert result["messages"] == 2
    assert result["matched"] == 1
    assert result["unmatched"] == 1
    assert result["replied"] == 1
    assert result["opened"] == 1 and result["clicked"] == 1

    # Raw report rows persisted.
    report = conn.execute("SELECT * FROM apollo_analytics_sync_report").fetchall()
    assert len(report) == 2
    assert {r["apollo_message_id"] for r in report} == {"m1", "m2"}

    # lead_outcomes folded: m1 mapped to lead 1.
    outcome = conn.execute("SELECT * FROM lead_outcomes WHERE lead_id = 1").fetchone()
    assert outcome["replied"] == 1
    assert outcome["reply_sentiment"] == "willing_to_meet"
    assert outcome["email"] == "alice@co.com"

    # Re-running is idempotent: no new report row, same outcome.
    pages2 = iter([{"emailer_messages": [
        {"id": "m1", "to_email": "alice@co.com", "status": "opened",
         "sent_at": "2026-09-05T10:00:00Z", "opens": 1, "replied": True}],
        "pagination": {"total_pages": 1}}])
    aa.sync_analytics_report(conn, key="secret", days=7,
                             _get=lambda *a, **kw: next(pages2))
    assert conn.execute("SELECT COUNT(*) FROM apollo_analytics_sync_report").fetchone()[0] == 2
    assert conn.execute("SELECT COUNT(*) FROM lead_outcomes").fetchone()[0] == 1