"""recipes (saved Apollo search recipes) DDL + CRUD guard.

The app is PostgreSQL-only; the apollo_recipes DDL must never drift back to
the SQLite AUTOINCREMENT idiom, which the PG wrapper can't translate and
which fails at parse time on Neon ("syntax error at or near AUTOINCREMENT").
sqlite can't execute the PG identity DDL, so the DDL is asserted on the
emitted SQL and CRUD flow is run against a sqlite table with ensure_table
stubbed out.
"""
import sqlite3

import recipes


class _CapturingConn:
    def __init__(self):
        self.executed = []

    def execute(self, sql, params=None):
        self.executed.append(sql)
        return self

    def commit(self):
        pass


def test_ensure_table_ddl_is_postgres_only():
    conn = _CapturingConn()
    recipes.ensure_table(conn)
    recipes_ddl, versions_ddl = conn.executed
    for ddl in (recipes_ddl, versions_ddl):
        assert "AUTOINCREMENT" not in ddl
        assert "?" not in ddl
    assert "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in recipes_ddl
    assert recipes_ddl.startswith("CREATE TABLE IF NOT EXISTS apollo_recipes")
    assert versions_ddl.startswith("CREATE TABLE IF NOT EXISTS apollo_recipe_versions")


def _sqlite_conn():
    conn = sqlite3.connect(":memory:")
    conn.row_factory = sqlite3.Row
    conn.execute(
        "CREATE TABLE apollo_recipes ("
        "id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, filters TEXT, created_at TEXT, "
        "runs INTEGER NOT NULL DEFAULT 0, "
        "leads_pulled INTEGER NOT NULL DEFAULT 0, "
        "qualified INTEGER NOT NULL DEFAULT 0, "
        "enriched INTEGER NOT NULL DEFAULT 0, "
        "sent INTEGER NOT NULL DEFAULT 0, "
        "replies INTEGER NOT NULL DEFAULT 0)"
    )
    conn.execute(
        "CREATE TABLE apollo_recipe_versions ("
        "id INTEGER PRIMARY KEY AUTOINCREMENT, recipe_id INTEGER NOT NULL, version INTEGER NOT NULL, "
        "filters TEXT, created_at TEXT, "
        "runs INTEGER NOT NULL DEFAULT 0, "
        "leads_pulled INTEGER NOT NULL DEFAULT 0, "
        "qualified INTEGER NOT NULL DEFAULT 0, "
        "enriched INTEGER NOT NULL DEFAULT 0, "
        "sent INTEGER NOT NULL DEFAULT 0, "
        "replies INTEGER NOT NULL DEFAULT 0)"
    )
    return conn


def test_recipe_crud_and_counters(monkeypatch):
    monkeypatch.setattr(recipes, "ensure_table", lambda conn: None)
    conn = _sqlite_conn()
    rid = recipes.create(conn, "health app founders", {"title": "Founder"})
    assert recipes.get(conn, rid)["name"] == "health app founders"

    recipes.record_run(conn, rid, leads_pulled=100, qualified=90, enriched=80)
    d = recipes.get(conn, rid)
    assert d["runs"] == 1
    assert d["leads_pulled"] == 100
    assert d["qualified_rate"] == 0.9
    assert d["reply_rate"] is None

    recipes.record_outcomes(conn, rid, sent=10, replies=2)
    d = recipes.get(conn, rid)
    assert d["sent"] == 10
    assert d["replies"] == 2
    assert d["reply_rate"] == 0.2

    assert [r["id"] for r in recipes.list_all(conn)] == [rid]

    recipes.delete(conn, rid)
    assert recipes.get(conn, rid) is None


def test_bad_filters_json_survives(monkeypatch):
    monkeypatch.setattr(recipes, "ensure_table", lambda conn: None)
    conn = _sqlite_conn()
    conn.execute("INSERT INTO apollo_recipes (name, filters, created_at) VALUES ('x', 'not-json', 't')")
    rid = conn.execute("SELECT id FROM apollo_recipes").fetchone()["id"]
    d = recipes.get(conn, rid)
    assert d["filters"] == {}


def test_recipe_versioning_preserves_historical_yield(monkeypatch):
    """Task 13: recipes are versioned objects. create() starts v1, run + outcomes
    accumulate on the current version, and update_filters() opens a NEW version
    for the new filters while freezing the OLD version's yield — so historical
    yield per filters-set is queryable."""
    monkeypatch.setattr(recipes, "ensure_table", lambda conn: None)
    conn = _sqlite_conn()

    rid = recipes.create(conn, "health founders", {"title": "Founder"})
    assert [v["version"] for v in recipes.versions(conn, rid)] == [1]

    # Two runs on v1 accumulate on version 1 only.
    recipes.record_run(conn, rid, leads_pulled=100, qualified=90, enriched=80)
    recipes.record_run(conn, rid, leads_pulled=50, qualified=40, enriched=35)
    recipes.record_outcomes(conn, rid, sent=10, replies=2)
    v1 = recipes.versions(conn, rid)
    assert len(v1) == 1
    assert v1[0]["runs"] == 2
    assert v1[0]["leads_pulled"] == 150
    assert v1[0]["reply_rate"] == 0.2

    # Editing filters opens a new version carrying the cumulative yield.
    recipes.update_filters(conn, rid, {"title": "CEO"})
    vs = recipes.versions(conn, rid)
    assert [v["version"] for v in vs] == [1, 2]
    # v1 is the historical (frozen) old-filters snapshot.
    assert vs[0]["filters"] == {"title": "Founder"} and vs[0]["runs"] == 2
    # v2 is the new filters, inheriting cumulative counters.
    assert vs[1]["filters"] == {"title": "CEO"}
    # current recipe now shows the new filters.
    assert recipes.get(conn, rid)["filters"] == {"title": "CEO"}

    # A run after the edit lands on the newest version (v2), not the old one.
    recipes.record_run(conn, rid, leads_pulled=25, qualified=20, enriched=15)
    vs = recipes.versions(conn, rid)
    assert vs[0]["runs"] == 2                    # v1 history frozen
    assert vs[1]["runs"] == 3
    assert vs[1]["leads_pulled"] == 175
    assert recipes.get(conn, rid)["runs"] == 3   # current cumulative count

    recipes.delete(conn, rid)
    assert recipes.versions(conn, rid) == []