"""campaigns DDL + CRUD guard (Phase 2).

The app is PostgreSQL-only; the campaigns DDL must use the PG identity idiom.
sqlite can't execute the PG identity DDL, so the DDL is asserted on the
emitted SQL and CRUD flow runs against a sqlite compat table with ensure_table
stubbed out — the same pattern as test_recipes.py.
"""
import sqlite3

import campaigns


class _CapturingConn:
    def __init__(self):
        self.executed = []

    def execute(self, sql, params=None):
        self.executed.append(sql)
        return self

    def commit(self):
        pass


def test_ensure_table_ddl_is_postgres_only():
    conn = _CapturingConn()
    campaigns.ensure_table(conn)
    ddl = conn.executed[0]
    assert "AUTOINCREMENT" not in ddl
    assert "?" not in ddl
    assert "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in ddl
    assert ddl.startswith("CREATE TABLE IF NOT EXISTS campaigns")
    assert "ship_plan TEXT" in ddl


def _sqlite_conn():
    conn = sqlite3.connect(":memory:")
    conn.row_factory = sqlite3.Row
    conn.execute(
        "CREATE TABLE campaigns ("
        "id INTEGER PRIMARY KEY AUTOINCREMENT, "
        "recipe_id INTEGER, session_id INTEGER, name TEXT, "
        "status TEXT NOT NULL DEFAULT 'reviewing', "
        "created_at TEXT, shipped_at TEXT, ship_plan TEXT)"
    )
    return conn


def test_campaign_create_and_get(monkeypatch):
    monkeypatch.setattr(campaigns, "ensure_table", lambda conn: None)
    conn = _sqlite_conn()
    cid = campaigns.create(conn, recipe_id=42, name="health founders sep26")
    camp = campaigns.get(conn, cid)
    assert camp["name"] == "health founders sep26"
    assert camp["recipe_id"] == 42
    assert camp["status"] == "reviewing"


def test_campaign_list_all(monkeypatch):
    monkeypatch.setattr(campaigns, "ensure_table", lambda conn: None)
    conn = _sqlite_conn()
    c1 = campaigns.create(conn, 1, "one")
    c2 = campaigns.create(conn, 2, "two")
    ids = [c["id"] for c in campaigns.list_all(conn)]
    assert ids == [c2, c1]  # DESC order


def test_campaign_set_session(monkeypatch):
    monkeypatch.setattr(campaigns, "ensure_table", lambda conn: None)
    conn = _sqlite_conn()
    cid = campaigns.create(conn, 1)
    campaigns.set_session(conn, cid, 77)
    assert campaigns.get(conn, cid)["session_id"] == 77


def test_campaign_mark_shipped(monkeypatch):
    monkeypatch.setattr(campaigns, "ensure_table", lambda conn: None)
    conn = _sqlite_conn()
    cid = campaigns.create(conn, 1)
    plan = '{"batches": [["2026-09-07", [1,2]]]}'
    campaigns.mark_shipped(conn, cid, ship_plan=plan)
    camp = campaigns.get(conn, cid)
    assert camp["status"] == "shipped"
    assert camp["ship_plan"] == plan
    assert camp["shipped_at"] is not None